kind: repositories
id: npm
type: group
ris: LKZ
repos:
  - repo: npm-repo-foo-group-lkz
    members:
      - npm-repo-foo-lkz
#  - repo: npm-repo-foo-group1231
#    members:
#      - npm-repo-foo-lkz