kind: "repositories"
id: "maven"
type: "proxy"
ris: "GDCR"
repos:
  - repo: gdcr-maven
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/gdcr-maven/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: gdcr-maven-lib
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/gdcr-maven-lib/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: gdcr-maven-proxy-group
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/gdcr-maven-proxy-group/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: gdcr-maven-snapshot
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/gdcr-maven-snapshot/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tsau-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tsau-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tsrm-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tsrm-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tslg-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tslg-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tstr-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tstr-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tsds-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tsds-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tsaj-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tsaj-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tsec-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tsec-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tssh-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tssh-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: plcm-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/plcm-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tsss-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tsss-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tsaj_trtl-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tsaj_trtl-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: pfomb-maven
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/pfomb-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: tssg-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/tssg-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: usbp-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/usbp-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb
  - repo: epaa-maven-pub
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/epaa-maven-pub/
    username: ci_si_gdcr@corp.dev.vtb