kind: "repositories"
id: "maven"
type: "proxy"
ris: "LKZ"
repos:
  - repo: lkz-maven
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/lkz-maven/
    username: ci_si_LKZ@corp.dev.vtb
  - repo: lkz-maven-lib
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/lkz-maven-lib/
    username: ci_si_LKZ@corp.dev.vtb
  - repo: lkz-maven-proxy-group
    remote_url: https://maven.repo-ci.sfera.inno.local/repository/lkz-maven-proxy-group/
    username: ci_si_LKZ@corp.dev.vtb