kind: "repositories"
id: "maven"
type: "group"
ris: "GDCR"
repos:
  - repo: gdcr-maven-group
    members:
      - gdcr-maven
      - gdcr-maven-snapshot
      - gdcr-maven-proxy-group
      - gdcr-maven-lib
  - repo: omni-proxy-group
    members:
      - tsau-maven-pub
      - tsrm-maven-pub
      - tslg-maven-pub
      - tstr-maven-pub
      - tsds-maven-pub
      - tsaj-maven-pub
      - tsec-maven-pub
      - tssh-maven-pub
      - plcm-maven-pub
      - tsss-maven-pub
      - tsaj_trtl-maven-pub
      - tssg-maven-pub
      - usbp-maven-pub
      - epaa-maven-pub