apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.jobName }}
data:
  {{- range  $path, $file :=  .Files.Glob ("configs/**/*.yaml") }}
  {{ base $path }}: |-
    {{- b64dec (toYaml $file) | toString | nindent 4 }}
  {{- end }}
