image:
  repository: nexus-repos-state
  tag: 1.0.0
  pullPolicy: IfNotPresent

securityContext:
  enable: false
  fsGroup: 1001120000
  runAsNonRoot: false
  runAsUser: 1001120000

jobName: nexus-repos-state
backoffLimit: 1
activeDeadLineSeconds: 360

env:
  public:
    NEXUS_URL: "http://127.0.0.1:8081/service/rest/v1/"
    NEXUS_PATH_TO_CONFIGS: /app/configs/
  secret:
    NEXUS_USER: "admin"
    NEXUS_USER_PASSWORD: "admin"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

jobAnnotations:
  "helm.sh/hook": post-install,post-upgrade
  "helm.sh/hook-weight": "-5"
  "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded